"use strict";
var a;
a = 10;
a = "ola";
var b = 10;
var ct = { id: 0, nome: '', fone: '', email: '' };
ct.id = 10;
ct.nome = "Maria";
ct.fone = "1234-5678";
ct.email = "maria@gmail.com";
console.log(ct);
